### PR TITLE
ASUSWRT-Merlin-LTS adaptations to test

### PR DESCRIPTION
**Pull request by dave14305**
with this PR, spdMerlin runs fine on ASUSWRT-Merlin-LTS 43D4j9527. Please test on Merlin. I think it's fine to just load the standard jquery.js and allow one to fail to load on the other firmware.

### CODE REVIEW

**Comment by jackyaz** [comment]
How does it run using my hosted jquery and validator js? i.e. is adding detect.js enough?

I would prefer to work against a known version of these files, if possible.

**Comment by dave14305** [comment]
Yes, it works fine either way. Just seems like an extra thing to maintain.

Sorry, no, the old jQuery isn't enough. the noConflict is still required on the fork.

**Comment by jackyaz** [comment]
OK cheers!

**Comment by jackyaz** [comment]
> Sorry, no, the old jQuery isn't enough. the noConflict is still required on the fork.

Weirdly, the last committed version seems to be newer than the one on Merlin, which is 1.10.2 i think? https://github.com/john9527/asuswrt-merlin/blob/374.43_2-update/release/src/router/www/jquery.js

**Comment by dave14305** [comment]
Yes but that’s from 2016. John hasn’t pushed his new code up yet with 3.x

**Comment by jackyaz** [comment]
> Yes but that’s from 2016. John hasn’t pushed his new code up yet with 3.x

Right, but If the "new" jQuery isn't referenced in the page at all I'm not sure how 1.10.2 from Merlin to require the noConflict.

**Comment by dave14305** [comment]
I think it should be inert, but I only learned about this a couple days ago. :-)

https://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/

**Comment by jackyaz** [comment]
It'd be useful to know which of the other js files use $ and conflict. What console errors do you get with spdmerlin's develop page as is?

**Comment by dave14305** [comment]
This is the conflict: https://github.com/john9527/asuswrt-merlin/blob/374.43_2-update/release/src/router/www/state.js#L1314

**Comment by jackyaz** [comment]
> This is the conflict: https://github.com/john9527/asuswrt-merlin/blob/374.43_2-update/release/src/router/www/state.js#L1314

OK, noConflict added. Having gone through state.js, it's just weird. I'm hosting detect.js too because I didn't want a 404 on Merlin :)

Looks good on Merlin, can you test the latest ASP from develop your end please?

**Comment by dave14305** [comment]
Already done. Looks good. Thank you.

**Comment by jackyaz** [comment]
> Already done. Looks good. Thank you.

Brilliant. I'll close this PR but tag you in my next commit :)

Many, many thanks!

**Pull request closed without merging**
